### ISSUE TITLE
Action failed when submodule changed

### ISSUE THREAD

**Issue by jim3ma** [ppremk/lfs-warning#144]
**Describe the bug**

When the PR contains a changed submodule, the action will failed with "Not found" error message.
This error message is come from [this code](https://github.com/ActionsDesk/lfs-warning/blob/v3.2/src/index.ts#L206)

**To Reproduce**

1. Update any submodule

**Expected behavior**

submodule should be ignore

**Screenshots**

[sample PR](https://github.com/dragonflyoss/Dragonfly2/runs/8136328955?check_suite_focus=true)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by spangaer** [comment]
FYI, easy to work around by defining them as `exclusionPatterns`

**Comment by dzmitry-lahoda** [comment]
at least can improve error

**Comment by dzmitry-lahoda** [comment]
I excluded submodules folders, did not helped.
