### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by AlekSi** [ppremk/lfs-warning#146]
I got that warning after using lfs-warning@v3.2:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actionsdesk/lfs-warning

**Comment by patspam** [comment]
Has been about 6 months.. is this GitHub Action still being maintained?

**Comment by BilbyFactor** [comment]
A fix for this was merged, but there has not been a new release since, @ppremk is that possible at present?

**Comment by ppremk** [comment]
👋🏽  folks. Pardon the delay. It has been some testing times. I will be getting to sorting this out by end of this week, when I have some time blocked. 

Appreciate the patience and support from you folks. 🙇🏽

**Comment by ZPascal** [comment]
@ppremk Do you have any news about the NodeJs switch?

**Comment by AlekSi** [comment]
Node 16 is going to be deprecated soon: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
